services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/psantueno/n8n-on-render
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: consultasdoblem@gmail.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: AdminWeb1*
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_HOST
        value: ia-assistant-crf.onrender.com
      - key: WEBHOOK_URL
        value: https://ia-assistant-crf.onrender.com/
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRES_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_POSTGRES_PORT
        value: "6543"
      - key: DB_POSTGRES_DATABASE
        value: postgres
      - key: DB_POSTGRES_USER
        value: postgres.agtplyqhkygpxzutcswl
      - key: DB_POSTGRES_PASSWORD
        value: perrodemadera56
      - key: DB_POSTGRES_SSLMODE
        value: require
