services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/psantueno/n8n-on-render
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: seba.antueno@gmail.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin
      - key: N8N_HOST
        value: ia-assistant-crf.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://ia-assistant-crf.onrender.com
      - key: N8N_PROTOCOL
        value: https
