services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/psantueno/n8n-on-render
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: claveSegura123
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
